apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: enketo-redis-cache
  namespace: odk-central
spec:
  version: "5.0.3-v1"
  configSource:
      configMap:
        name: redis-config-cache
  storage:
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

