apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odk-central-mgmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  source:
    repoURL: "https://gitlab.com/makkus/odk-central-kubernetes.git"
    targetRevision: HEAD
    path: "manifests/apps/mgmt"
  destination:
    server: https://kubernetes.default.svc
    namespace: "argocd"
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
