apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odk-central-enketo-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: odk-central
  project: default
  source:
    path: manifests/odk-central/enketo-backend
    repoURL: https://gitlab.com/makkus/odk-central-kubernetes.git
    targetRevision: HEAD
#  directory:
#    recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
