apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odk-central-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "19"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: odk-central
  project: default
  source:
    path: manifests/odk-central/postgres
    repoURL: https://github.com/ferjavrec/odk-central.git
    targetRevision: HEAD
#  directory:
#    recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
