apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odk-central-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mgmt
  project: default
  source:
    path: manifests/mgmt/cert-manager
    repoURL: https://gitlab.com/makkus/odk-central-kubernetes.git
    targetRevision: HEAD
#  directory:
#    recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
