apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odk-central-ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mgmt
  project: default
  source:
    path: manifests/mgmt/ingress-nginx
    repoURL: https://github.com/ferjavrec/odk-central.git
    targetRevision: HEAD
#  directory:
#    recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
